/* soapUPCBWebServiceSoapService.h
   Generated by gSOAP 2.8.3 from upcb.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapUPCBWebServiceSoapService_H
#define soapUPCBWebServiceSoapService_H
#include "soapH.h"
class SOAP_CMAC UPCBWebServiceSoapService : public soap
{ public:
	/// Constructor
	UPCBWebServiceSoapService();
	/// Constructor with copy of another engine state
	UPCBWebServiceSoapService(const struct soap&);
	/// Constructor with engine input+output mode control
	UPCBWebServiceSoapService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	UPCBWebServiceSoapService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~UPCBWebServiceSoapService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void UPCBWebServiceSoapService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	UPCBWebServiceSoapService *copy() SOAP_PURE_VIRTUAL;
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'AddProgram' (returns error code or SOAP_OK)
	virtual	int AddProgram(_ns1__AddProgram *ns1__AddProgram, _ns1__AddProgramResponse *ns1__AddProgramResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'StartProgram' (returns error code or SOAP_OK)
	virtual	int StartProgram(_ns1__StartProgram *ns1__StartProgram, _ns1__StartProgramResponse *ns1__StartProgramResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'StopProgram' (returns error code or SOAP_OK)
	virtual	int StopProgram(_ns1__StopProgram *ns1__StopProgram, _ns1__StopProgramResponse *ns1__StopProgramResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetBoardInfo' (returns error code or SOAP_OK)
	virtual	int GetBoardInfo(_ns1__GetBoardInfo *ns1__GetBoardInfo, _ns1__GetBoardInfoResponse *ns1__GetBoardInfoResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetDevices' (returns error code or SOAP_OK)
	virtual	int GetDevices(_ns1__GetDevices *ns1__GetDevices, _ns1__GetDevicesResponse *ns1__GetDevicesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetDrivers' (returns error code or SOAP_OK)
	virtual	int GetDrivers(_ns1__GetDrivers *ns1__GetDrivers, _ns1__GetDriversResponse *ns1__GetDriversResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetPrograms' (returns error code or SOAP_OK)
	virtual	int GetPrograms(_ns1__GetPrograms *ns1__GetPrograms, _ns1__GetProgramsResponse *ns1__GetProgramsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetProgram' (returns error code or SOAP_OK)
	virtual	int GetProgram(_ns1__GetProgram *ns1__GetProgram, _ns1__GetProgramResponse *ns1__GetProgramResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetProgramStatus' (returns error code or SOAP_OK)
	virtual	int GetProgramStatus(_ns1__GetProgramStatus *ns1__GetProgramStatus, _ns1__GetProgramStatusResponse *ns1__GetProgramStatusResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'GetRunningProgramsStatus' (returns error code or SOAP_OK)
	virtual	int GetRunningProgramsStatus(_ns1__GetRunningProgramsStatus *ns1__GetRunningProgramsStatus, _ns1__GetRunningProgramsStatusResponse *ns1__GetRunningProgramsStatusResponse) SOAP_PURE_VIRTUAL;
};
#endif
